### ISSUE TITLE
Unable to connect to k8s master

### ISSUE THREAD

**Issue by rimusz** [kubernetes-ui/kubernetes-ui-docker#1]
I tried to run
docker run -e ENV_K8S_API_SERVER="http://some_ip/api/v1beta2" -t -p 8001:80 kubernetes-ui
but in Dashboard did not see any master/nodes.

**Comment by preillyme** [comment]
@rimusz do you see any errors in your javascript console in your web browser?

**Comment by rimusz** [comment]
Yes, seeing these errors:
![screenshot 2015-04-11 22 40 52](https://cloud.githubusercontent.com/assets/5215395/7103378/f6781ab4-e09b-11e4-9f88-505e3060f183.png)

**Comment by rimusz** [comment]
My fault, did  not see that `kube-apiserver' needs to be started with `--cors_allowed_origins=.*`
